version: "3.7"

services:
  db:
    container_name: mysql
    hostname: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: gorello
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - gorellonet
    volumes:
      - ./:/docker-entrypoint-initdb.d

  gorelloapi:
    container_name: gorelloapi
    hostname: gorelloapi
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - gorellonet
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
    links:
      - db
    labels:
      kompose.service.type: LoadBalancer

networks:
  gorellonet:
    driver: bridge
